Schema fields client
swiftype/swiftype-app-search-python pull request #23
Opened 2019-07-17 03:28 UTC by CorrosiveKid

Closes #22

2019-07-19 01:41 UTC, JasonStoltz commented
Hey @CorrosiveKid, thank you for the contribution. Before we can merge this, we require that you sign a CLA.

2019-07-19 04:10 UTC, CorrosiveKid commented
> Hey @CorrosiveKid, thank you for the contribution. Before we can merge this, we require that you sign a CLA: https://www.elastic.co/contributor-agreement.

Done!

2019-07-19 16:54 UTC, JasonStoltz requested changes
I just noticed one small typo, it works great otherwise.

2019-07-19 16:54 UTC, JasonStoltz commented on swiftype_app_search/client.py
> +        Create new schema fields or update the fields if they alreadt exists.
```suggestion
        Create new schema fields or update the fields if they already exists.
```

2019-07-20 06:56 UTC, CorrosiveKid commented
> I just noticed one small typo, it works great otherwise.

Thanks for that, fixed!

2019-07-22 20:21 UTC, JasonStoltz approved these changes

2019-07-22 20:22 UTC, merged